# render.yaml
services:
  - type: web
    name: tictac-auto-deploy
    env: node
    plan: free
    buildCommand: |
      npm install
      # Force fresh clone every deploy
      node server.js --download
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FORCE_REDEPLOY
        value: true
    autoDeploy: true
